const chronicles = [
  { realm:'The Threshold', beast:'Malgrath the Dread', fairy:'Empress Dryad of Ashwood', birth:'beneath the first gate, where an ancient world-root drank iron from buried armies', gift:'moss, stone, and every green thing that remembers rain', crown:'the vinebound throne', ruin:'roots split the gatehouse and yellow eyes watched from every hill' },
  { realm:'Ashwood Frontier', beast:'Stoneback Krul', fairy:'Empress Pyra of the Caldera', birth:'when the mountain swallowed a city and coughed its bells back as molten teeth', gift:'flame, forgecraft, and the courage of those who build beside ruin', crown:'the ember throne', ruin:'iron bridges sagged into lava and ash buried the frontier roads' },
  { realm:'The Crucible', beast:'Glacius the Eternal', fairy:'Empress Frost of Glacius Peak', birth:'inside a glacier that had imprisoned the last breath of winter for ten thousand years', gift:'ice, clear judgment, and the patience of rivers sleeping beneath snow', crown:'the sapphire throne', ruin:'blue spires speared the valleys and whole banners froze before touching earth' },
  { realm:'Ironveil Fortress', beast:'Vreth the Unseen', fairy:'Empress Vreth of Shadowfen', birth:'from the shadow cast by the first dead oak when moonlight found the poisoned fen', gift:'old runes, hidden paths, and the stubborn memory of ruined kingdoms', crown:'the violet throne', ruin:'toxic moss lit empty halls while soldiers vanished between one heartbeat and the next' },
  { realm:'The Obsidian March', beast:'Ignarax the Burning', fairy:'Empress Jade of the Oasis', birth:'where a desert sun struck a buried god-bone and woke the sand into scales', gift:'water, jade gardens, and mercy carried across merciless distances', crown:'the jade throne', ruin:'wells became glass and sandstone towers walked away inside the storm' },
  { realm:'Dreadspire Academy', beast:'Sol-Varen the Radiant', fairy:'Empress Zephyr of Cloudspire', birth:'from a fallen feather of the sun that landed upon the highest marble island', gift:'wind, learning, and the bright aqueducts that joined cities above the clouds', crown:'the solar throne', ruin:'golden fire judged every library and shattered islands rained upon the world below' },
  { realm:'The Forge Eternal', beast:'Duskbone Revenant', fairy:'Empress Spectral of the Deeps', birth:'when the bones of nameless kings were piled over a green soul-flame that refused to die', gift:'rest, remembrance, and safe passage through the caverns of the dead', crown:'the bone throne', ruin:'chains sealed the gates and the honored dead rose hungry beneath spectral fire' },
  { realm:'Shadowmere Depths', beast:'Thundercoil Zarak', fairy:'Empress Lira of Mirewood', birth:'where seven lightning bolts struck one ridge and braided themselves around an unhatched wyvern', gift:'stormwater, song, and the beacons that guided ships through black weather', crown:'the storm throne', ruin:'lightning rods bent toward villages and thunder erased the names carved on their doors' },
  { realm:'Crimson Summit', beast:'Nyxara the Void', fairy:'Empress Cosma of the Void', birth:'after a star died beyond the rim of heaven. Its heart collapsed into a void, and one burning shard fell through this universe. The stone cracked, and Nyxara crawled from it with many blue eyes already open', gift:'gravity, starlight, and the paths between places mortal maps cannot join', crown:'the void throne', ruin:'obsidian islands floated loose while homes and bodies forgot which way was down' },
  { realm:'The War Council', beast:'Gorvek the Ancient', fairy:'Empress Sol of the Golden Citadel', birth:'when the first titan laid down his bronze crown and the metal remembered every war it had witnessed', gift:'law, honorable combat, and the strength that raises cities without enslaving them', crown:'the titan throne', ruin:'colossal statues marched, arena gates closed, and bronze legions answered a dragon crowned in red' }
];

export const REGIONAL_CHRONICLES = chronicles.map((r) => [
  `Come nearer, wanderer, and hear what the stones of ${r.realm} remember. ${r.beast} was born ${r.birth}. It did not hatch helplessly. It entered the elder world with hunger, memory, and a claim upon all it saw. The first witnesses mistook its silence for ignorance. By dawn, they understood that an ancient will had merely been choosing where to begin. Herds fled before its shadow reached them. Wells trembled when it slept beneath the horizon. Priests placed bowls of salt at every threshold, while hunters returned with weapons untouched and faces emptied of courage. Even then, the beast did not hurry. It learned the roads, the seasons, and the names that frightened our children.`,
  `Long before your Scythe crossed our roads, ${r.fairy} guarded ${r.realm}. Hers was ${r.gift}. From ${r.crown}, she kept covenant with farmer, mason, spirit, and sovereign alike. When omens named ${r.beast}, she did not flee. She gathered her people, opened the old armories, and rode toward the horizon where the beast had darkened the sky. I remember the bells calling every village to shelter. I remember her standard moving against the fleeing crowd like a lone star swimming upstream. Smiths worked until their hands bled, children carried water to the walls, and the old sang the realm's first hymns. For one bright hour, fear itself seemed ashamed to stand among us.`,
  `I watched their war, and age has not softened it. The Empress struck first, and for three nights the heavens answered her. On the fourth, ${r.beast} broke her guard with a cunning no beast should possess. It chained her power beneath ${r.crown}, not to kill her, but to drink slowly from everything she protected. Thus the keeper became the prisoner, and the dragon became king. Her last command was not for rescue, but remembrance. We buried her banners beneath common hearths and taught her true name as a cradle song. Above us, the beast remade the palace into a wound that could be seen for leagues. Each season its chains tightened, and each season the light in the realm grew thinner.`,
  `Then ${r.ruin}. Those who survived kept one forbidden prophecy. A warrior would arrive after the kingdom had forgotten victory. No royal blood would guide that hand. No ancient army would march behind it. The stranger would bear a Scythe awakened by completed vows, and each honest deed would become a key. We preserved these words for you, though we did not know your face. The prophecy passed from baker to ferryman, from wounded soldier to child, hidden inside ordinary greetings. Dragon-priests burned libraries searching for it, yet never thought to question the songs of washerwomen. We pictured your coming a thousand ways. None imagined you would look so mortal, or that your greatest weapon would be the promises you refused to abandon.`,
  `Now I set down what our descendants must remember. The Scythe warrior entered the fallen realm and met ${r.beast} beneath a wounded sky. Steel answered scale. Will answered terror. When the final stroke fell, the dragon's dominion broke and the chains around ${r.fairy} became dust. Bells long buried began ringing beneath the earth. Doors opened to sunlight that families had known only through stories. ${r.fairy} rose from ${r.crown}, wounded but unbowed, and the old covenant breathed again through ${r.gift}. ${r.realm} did not begin with your arrival, wanderer, but by your victory its long story was permitted to continue. Remember that distinction. You are not the owner of this world, but the hand that returned its future.`
]);
